name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow manually'

jobs:
  build:
    runs-on: ubuntu-latest
    # use strategy matrix build images
    env:
      DOCKER_REPO: "bitcoin-core"
    strategy:
      matrix:
        image:
          - name: 25-alpine
            context: "./25/alpine"
          - name: 25-alpine-tor
            context: "./25/alpine/tor"
          - name: 25-ubuntu
            context: "./25/ubuntu"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ matrix.image.name }} ${{ matrix.image.context }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ matrix.image.name }}